import { Injectable } from '@angular/core';
import { Palette } from '../models/types';

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  exportCss(palette: Palette) {
    let css = `/* ${palette.paletteName} - Generated by ChromaGen AI */\n:root {\n`;
    palette.colors.forEach((color, index) => {
      const name = color.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
      css += `  --color-${name}-${index + 1}: ${color.hex};\n`;
    });
    css += `}\n`;
    this.downloadFile(css, `${this.slugify(palette.paletteName)}.css`, 'text/css');
  }

  exportJson(palette: Palette) {
    const json = JSON.stringify(palette, null, 2);
    this.downloadFile(json, `${this.slugify(palette.paletteName)}.json`, 'application/json');
  }

  exportPng(palette: Palette) {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Canvas Settings
    const width = 800;
    const height = 600;
    const padding = 40;
    const headerHeight = 100;
    
    canvas.width = width;
    canvas.height = height;

    // Background
    ctx.fillStyle = '#0f172a'; // Slate 900
    ctx.fillRect(0, 0, width, height);

    // Title
    ctx.font = 'bold 32px Inter, sans-serif';
    ctx.fillStyle = '#ffffff';
    ctx.fillText(palette.paletteName, padding, 60);

    ctx.font = '16px Inter, sans-serif';
    ctx.fillStyle = '#94a3b8'; // Slate 400
    ctx.fillText('Generated by ChromaGen AI', padding, 90);

    // Colors
    const colorWidth = (width - (padding * 2)) / palette.colors.length;
    const swatchHeight = height - headerHeight - padding * 2;
    const startY = headerHeight;

    palette.colors.forEach((color, i) => {
      const x = padding + (i * colorWidth);
      
      // Draw Swatch
      ctx.fillStyle = color.hex;
      ctx.fillRect(x, startY, colorWidth, swatchHeight);

      // Draw Hex Label
      ctx.fillStyle = color.textColor || (this.getContrastColor(color.hex) === '#1e293b' ? '#000' : '#fff');
      
      // Hex Background pill
      const textX = x + 15;
      const textY = startY + swatchHeight - 20;
      
      ctx.font = 'bold 14px monospace';
      ctx.fillText(color.hex, textX, textY);
      
      ctx.font = '12px sans-serif';
      ctx.fillText(color.name, textX, textY - 20);
    });

    const dataUrl = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.download = `${this.slugify(palette.paletteName)}.png`;
    link.href = dataUrl;
    link.click();
  }

  private downloadFile(content: string, filename: string, type: string) {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  }

  private slugify(text: string): string {
    return text.toString().toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w\-]+/g, '')
      .replace(/\-\-+/g, '-')
      .replace(/^-+/, '')
      .replace(/-+$/, '');
  }

  private getContrastColor(hex: string): string {
    const r = parseInt(hex.substr(1, 2), 16);
    const g = parseInt(hex.substr(3, 2), 16);
    const b = parseInt(hex.substr(5, 2), 16);
    const yiq = ((r * 299) + (g * 587) + (b * 114)) / 1000;
    return (yiq >= 128) ? '#1e293b' : '#f8fafc';
  }
}
